import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  function myFunction(e) {
    console.log(e);
    var x = document.getElementById('1');
    if (x.style.display === 'none') {
      x.style.display = 'block';
    } else {
      x.style.display = 'none';
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* Upper card */}
        <div className={styles.card}>
          <div className={styles.container}>
            <p className={styles.balanceText}>My Balance</p>
            <p className={styles.balance}>$921.48</p>
          </div>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img className={styles.logo} src="/images/logo.svg" alt="logo" />
        </div>
        {/* Lower card */}
        <div className={styles.card2}>
          <div className={styles.container}>
            <h1 className={styles.title}>Spending - Last 7 days</h1>
            {/* Column ? */}
            <div className={styles.chart}>
              <div className={styles.chartRow}>
                <label id="1" className={styles.label}>
                  $126
                </label>
                <div
                  onClick={myFunction}
                  name="1"
                  style={{ height: 0.4 * 140 + 'px' }}
                  className={styles.chartPilar}
                ></div>
                <p>mon</p>
              </div>
              <div className={styles.chartRow}>
                <div
                  style={{ height: 80 + 'px' }}
                  className={styles.chartPilar}
                ></div>
                <p>tue</p>
              </div>
              <div className={styles.chartRow}>
                <div
                  style={{ height: 135 + 'px' }}
                  className={styles.chartPilar}
                ></div>
                <p>wed</p>
              </div>
              <div className={styles.chartRow}>
                <div
                  style={{ height: 70 + 'px' }}
                  className={styles.chartPilar}
                ></div>
                <p>thu</p>
              </div>
              <div className={styles.chartRow}>
                <div
                  style={{ height: 50 + 'px' }}
                  className={styles.chartPilar}
                ></div>
                <p>fri</p>
              </div>
              <div className={styles.chartRow}>
                <div
                  style={{ height: 90 + 'px' }}
                  className={styles.chartPilar}
                ></div>
                <p>sat</p>
              </div>
              <div className={styles.chartRow}>
                <div
                  style={{ height: 55 + 'px' }}
                  className={styles.chartPilar}
                ></div>
                <p>sun</p>
              </div>
            </div>
            <span className={styles.divider}></span>
            {/* Columns */}
            <div>
              <p>Total this months</p>
              <p>$478.33</p>
            </div>
            <div>
              <p>+2.4%</p>
              <p>from last month</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
